#!/bin/sh

# 
# To be run when this script receives the EXIT signal
function capture_on_exit () {
	# Store the exit code
	result=$?

	# Fix our stdout and stderr
	exec 1>&11 2>&12 11>&- 12>&-

	# If we have a non-zero exit code, display the buffered output
	if [[ $result -ne 0 ]]; then
		echo "$1 exited with error code $result"
		cat $2
	fi

	# Remove the buffered output file
	rm -f $2
}

# Create the temorary output buffer
capture_outfile=$(mktemp)

# Store stdout and stderr, then redirect them to the buffer
exec 11>&1 12>&2 &>$capture_outfile

# Set our exit trap to display any errors and do our clean up 
trap "capture_on_exit $1 $capture_outfile" EXIT SIGHUP SIGINT SIGTERM

bash -e $*