#! /bin/bash -e

cat <<EOF
------------------------------------------------------------------------
This is an example hook to demonstrate commit-msg hook functionality.
If you are seeing this, it means you've successfully installed the 
hooks for this repository. Disable it like this:

    git config --bool hooks.commit-msg-jira.enabled false

or just delete the file (.githooks/commit-msg-jira).
------------------------------------------------------------------------

EOF

# Fails unless the JIRA- prefix is found in the commit msg
if ! grep "JIRA-[[:digit:]]\+" &>/dev/null <$1; then
	echo "You must provide a JIRA-#### ticket number in your commit message."
	exit 1
fi
