#! /bin/bash

HOOK=$(basename $0)

assign URL=repository.url BEFORE=before AFTER=after REF=ref
LOC=${URL%/*/*}; LOC=${URL#${LOC}/}
REPOS_DIR=/var/opt/github-webhook/repos
REPO_DIR=$REPOS_DIR/$LOC

# Clone repo if necessary
[[ -e $REPO_DIR ]] || { mkdir -p $REPO_DIR && git clone --bare $URL $REPO_DIR >/dev/null; }

if [[ -x $REPO_DIR/hooks/$HOOK ]]; then
    # Navigate to the repository directory
    pushd $REPO_DIR >/dev/null

    # Pull down the latest refs
    git fetch origin +refs/heads/*:refs/heads/* >/dev/null

    # Run the hook
    hooks/$HOOK $BEFORE $AFTER $REF
fi


