#! /bin/bash -e

# Check for the configured gittools path first, then look in the current repository (perhaps you submoduled it)
if gittools=$(git config --get zynga.gittools.path || echo './gittools') && [[ -e $gittools ]]; then
	# Invoke the multiplexer
	export gittools
	$gittools/hooks_runner $(basename $0) $*
else
	echo "git $(basename $0) hooks failed. You must provide the path to gittools:"
	echo "    git config [--global] --add zynga.gittools.path </path/to/gittools>"
	exit 1	
fi
