#! /bin/bash

# Pipe a WebHook HTTP request to this script to override the default of using sample-http-post

DIR=$(cd $(dirname $0) && pwd)
[[ -t 0 ]] && INPUT=$DIR/sample-http-post || INPUT=
HOST=${1:-localhost}
PORT=${2:-9000}

OUTPUT=$(mktemp)
trap "rm -f $OUTPUT" EXIT

cat $INPUT | nc $HOST $PORT | tee $OUTPUT
head -n1 $OUTPUT | grep -q "HTTP/1.1 200 OK"
