#! /bin/bash

# Pipe a WebHook HTTP request to this script to override the default of using sample-http-post

DIR=$(cd $(dirname $0) && pwd)
[[ -t 0 ]] && INPUT=$DIR/sample-http-post || INPUT=

cat $INPUT | sudo -u git $DIR/../server $DIR/../actions/post-receive
